import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { MiniProcGeneratedModule, MiniProcGeneratedSharedModule } from './generated/module.js';
import { MiniProcValidator, registerValidationChecks } from './mini-proc-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MiniProcAddedServices = {
    validation: {
        MiniProcValidator: MiniProcValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MiniProcServices = LangiumServices & MiniProcAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MiniProcModule: Module<MiniProcServices, PartialLangiumServices & MiniProcAddedServices> = {
    validation: {
        MiniProcValidator: () => new MiniProcValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMiniProcServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MiniProc: MiniProcServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MiniProcGeneratedSharedModule
    );
    const MiniProc = inject(
        createDefaultModule({ shared }),
        MiniProcGeneratedModule,
        MiniProcModule
    );
    shared.ServiceRegistry.register(MiniProc);
    registerValidationChecks(MiniProc);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, MiniProc };
}
